# Generated by Django 3.1.3 on 2022-05-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(default='question text', max_length=300),
        ),
        migrations.AlterField(
            model_name='question',
            name='grade',
            field=models.FloatField(default=5.0),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(default='question text', max_length=300),
        ),
    ]
